
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema PetValley
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema PetValley
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `PetValley` DEFAULT CHARACTER SET utf8 ;
USE `PetValley` ;

-- -----------------------------------------------------
-- Table `PetValley`.`ADDRESS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PetValley`.`ADDRESS` (
  `ID_ADDRESS` INT NOT NULL AUTO_INCREMENT,
  `POSTAL_CODE` VARCHAR(8) NOT NULL,
  `LOCATION` VARCHAR(255) NOT NULL,
  `TYPE_LOCATION` VARCHAR(45) NOT NULL,
  `NEIGHBORHOOD` VARCHAR(255) NOT NULL,
  `CITY` VARCHAR(255) NOT NULL,
  `STATE` VARCHAR(2) NOT NULL,
  `NUMBER_HOUSE` INT NOT NULL,
  `COMPLEMENT` VARCHAR(255) NULL,
  PRIMARY KEY (`ID_ADDRESS`),
  UNIQUE INDEX `ID_ADDRESS_UNIQUE` (`ID_ADDRESS` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PetValley`.`USER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PetValley`.`USER` (
  `ID_USER` INT NOT NULL AUTO_INCREMENT,
  `CODE_CPF` VARCHAR(11) NOT NULL,
  `NAME` VARCHAR(100) NOT NULL,
  `SURNAME` VARCHAR(45) NOT NULL,
  `BIRTHDATE` DATETIME NOT NULL,
  `SEX` VARCHAR(9) NOT NULL,
  `EMAIL` VARCHAR(255) NOT NULL,
  `PASSWORD` VARCHAR(32) NOT NULL,
  `CREATE_TIME` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `CELLPHONE` VARCHAR(11) NOT NULL,
  `PHONE_NUMBER` VARCHAR(11) NULL,
  `IMAGE` BLOB NULL,
  `ID_ADDRESS_FK` INT NOT NULL,
  PRIMARY KEY (`ID_USER`),
  INDEX `fk_USER_ADDRESS_idx` (`ID_ADDRESS_FK` ASC),
  UNIQUE INDEX `ID_USER_UNIQUE` (`ID_USER` ASC),
  CONSTRAINT `fk_USER_ADDRESS`
    FOREIGN KEY (`ID_ADDRESS_FK`)
    REFERENCES `PetValley`.`ADDRESS` (`ID_ADDRESS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PetValley`.`USER_GROUPS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PetValley`.`USER_GROUPS` (
  `ID_USER_GROUPS` INT NOT NULL AUTO_INCREMENT,
  `NAME_GROUP` VARCHAR(15) NOT NULL,
  `DESCRIPTION` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`ID_USER_GROUPS`),
  UNIQUE INDEX `ID_USER_GROUPS_UNIQUE` (`ID_USER_GROUPS` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PetValley`.`INTERNAL_USER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PetValley`.`INTERNAL_USER` (
  `POST` VARCHAR(45) NOT NULL,
  `ADMISSION_DATE` DATETIME NOT NULL,
  `SHIFT` VARCHAR(8) NOT NULL,
  `IS_VOLUNTEER` TINYINT NOT NULL,
  `WORK_DAYS` VARCHAR(255) NOT NULL,
  `DEMISSION_DATE` DATETIME NULL,
  `CRMV` VARCHAR(10) NULL,
  `CRMV_UF` VARCHAR(2) NULL,
  `ID_USER_FK` INT NOT NULL,
  `ID_USER_GROUPS_FK` INT NOT NULL,
  PRIMARY KEY (`ID_USER_FK`),
  INDEX `fk_INTERNAL_USER_USER_GROUPS1_idx` (`ID_USER_GROUPS_FK` ASC),
  CONSTRAINT `fk_INTERNAL_USER_USER1`
    FOREIGN KEY (`ID_USER_FK`)
    REFERENCES `PetValley`.`USER` (`ID_USER`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_INTERNAL_USER_USER_GROUPS1`
    FOREIGN KEY (`ID_USER_GROUPS_FK`)
    REFERENCES `PetValley`.`USER_GROUPS` (`ID_USER_GROUPS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PetValley`.`QUESTIONNAIRE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PetValley`.`QUESTIONNAIRE` (
  `ID_QUESTIONNAIRE` INT NOT NULL AUTO_INCREMENT,
  `QUESTION_1` INT NOT NULL,
  `QUESTION_2` VARCHAR(3) NOT NULL,
  `QUESTION_3` VARCHAR(16) NOT NULL,
  `QUESTION_3-1` VARCHAR(12) NOT NULL,
  `QUESTION_4` VARCHAR(3) NOT NULL,
  `QUESTION_4-1` VARCHAR(8) NOT NULL,
  `QUESTION_4-2` VARCHAR(3) NOT NULL,
  `QUESTION_5` VARCHAR(3) NOT NULL,
  `QUESTION_5_COMPLEMENT` VARCHAR(50) NOT NULL,
  `QUESTION_6` DECIMAL(9) NOT NULL,
  `QUESTION_7` VARCHAR(3) NOT NULL,
  `QUESTION_7-1` VARCHAR(50) NOT NULL,
  `QUESTION_7-2` VARCHAR(50) NOT NULL,
  `QUIZ_DATE` DATETIME NOT NULL,
  `QUESTIONS_FILE` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`ID_QUESTIONNAIRE`),
  UNIQUE INDEX `ID_QUESTIONNAIRE_UNIQUE` (`ID_QUESTIONNAIRE` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PetValley`.`EXTERNAL_USER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PetValley`.`EXTERNAL_USER` (
  `ID_USER_FK` INT NOT NULL,
  `ID_QUESTIONNAIRE_FK` INT NULL,
  PRIMARY KEY (`ID_USER_FK`),
  INDEX `fk_EXTERNAL_USER_QUESTIONNAIRE1_idx` (`ID_QUESTIONNAIRE_FK` ASC),
  UNIQUE INDEX `ID_USER_FK_UNIQUE` (`ID_USER_FK` ASC),
  CONSTRAINT `fk_EXTERNAL_USER_USER1`
    FOREIGN KEY (`ID_USER_FK`)
    REFERENCES `PetValley`.`USER` (`ID_USER`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_EXTERNAL_USER_QUESTIONNAIRE1`
    FOREIGN KEY (`ID_QUESTIONNAIRE_FK`)
    REFERENCES `PetValley`.`QUESTIONNAIRE` (`ID_QUESTIONNAIRE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PetValley`.`TYPE_SUPPLY`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PetValley`.`TYPE_SUPPLY` (
  `ID_TYPE_SUPPLY` INT NOT NULL AUTO_INCREMENT,
  `NAME_SUPPLY` VARCHAR(45) NOT NULL,
  `UNIT` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`ID_TYPE_SUPPLY`),
  UNIQUE INDEX `ID_TYPE_SUPPLY_UNIQUE` (`ID_TYPE_SUPPLY` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PetValley`.`SUPPLY`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PetValley`.`SUPPLY` (
  `ID_SUPPLY` INT NOT NULL AUTO_INCREMENT,
  `DESCRIPTION` VARCHAR(255) NOT NULL,
  `EXPIRATION_DATE` DATETIME NOT NULL,
  `ENTRY_DATE` DATETIME NOT NULL,
  `QUANTITY` INT NOT NULL,
  `UPTADE_DATE` DATETIME NULL,
  `ID_USER_FK` INT NOT NULL,
  `ID_TYPE_SUPPLY` INT NOT NULL,
  PRIMARY KEY (`ID_SUPPLY`),
  INDEX `fk_SUPPLY_INTERNAL_USER1_idx` (`ID_USER_FK` ASC),
  INDEX `fk_SUPPLY_TYPE_SUPPLY1_idx` (`ID_TYPE_SUPPLY` ASC),
  UNIQUE INDEX `ID_SUPPLY_UNIQUE` (`ID_SUPPLY` ASC),
  CONSTRAINT `fk_SUPPLY_INTERNAL_USER1`
    FOREIGN KEY (`ID_USER_FK`)
    REFERENCES `PetValley`.`INTERNAL_USER` (`ID_USER_FK`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SUPPLY_TYPE_SUPPLY1`
    FOREIGN KEY (`ID_TYPE_SUPPLY`)
    REFERENCES `PetValley`.`TYPE_SUPPLY` (`ID_TYPE_SUPPLY`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PetValley`.`VISIT_ANIMAL`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PetValley`.`VISIT_ANIMAL` (
  `ID_VISIT_ANIMAL` INT NOT NULL AUTO_INCREMENT,
  `VISIT_DATE` DATETIME NOT NULL,
  `ID_USER_FK` INT NOT NULL,
  PRIMARY KEY (`ID_VISIT_ANIMAL`),
  INDEX `fk_VISIT_ANIMAL_EXTERNAL_USER1_idx` (`ID_USER_FK` ASC),
  UNIQUE INDEX `ID_VISIT_ANIMAL_UNIQUE` (`ID_VISIT_ANIMAL` ASC),
  CONSTRAINT `fk_VISIT_ANIMAL_EXTERNAL_USER1`
    FOREIGN KEY (`ID_USER_FK`)
    REFERENCES `PetValley`.`EXTERNAL_USER` (`ID_USER_FK`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PetValley`.`DOCUMENT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PetValley`.`DOCUMENT` (
  `ID_DOCUMENT` INT NOT NULL AUTO_INCREMENT,
  `TYPE_DOCUMENT` VARCHAR(45) NOT NULL,
  `IMAGE_DOCUMENT` BLOB NOT NULL,
  `DESCRIPTION` VARCHAR(255) NOT NULL,
  `ID_USER_FK` INT NOT NULL,
  PRIMARY KEY (`ID_DOCUMENT`),
  INDEX `fk_DOCUMENT_EXTERNAL_USER1_idx` (`ID_USER_FK` ASC),
  UNIQUE INDEX `ID_DOCUMENT_UNIQUE` (`ID_DOCUMENT` ASC),
  CONSTRAINT `fk_DOCUMENT_EXTERNAL_USER1`
    FOREIGN KEY (`ID_USER_FK`)
    REFERENCES `PetValley`.`EXTERNAL_USER` (`ID_USER_FK`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PetValley`.`VISIT_HOUSE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PetValley`.`VISIT_HOUSE` (
  `ID_VISIT_HOUSE` INT NOT NULL AUTO_INCREMENT,
  `VISIT_DATE` DATETIME NOT NULL,
  `IS_VISIT` TINYINT NOT NULL,
  `DESCRIPTION` VARCHAR(255) NOT NULL,
  `INTERNAL_ID_USER_FK` INT NOT NULL,
  `EXTERNAL_ID_USER_FK` INT NOT NULL,
  PRIMARY KEY (`ID_VISIT_HOUSE`),
  INDEX `fk_VISIT_HOUSE_INTERNAL_USER1_idx` (`INTERNAL_ID_USER_FK` ASC),
  INDEX `fk_VISIT_HOUSE_EXTERNAL_USER1_idx` (`EXTERNAL_ID_USER_FK` ASC),
  UNIQUE INDEX `ID_VISIT_HOUSE_UNIQUE` (`ID_VISIT_HOUSE` ASC),
  CONSTRAINT `fk_VISIT_HOUSE_INTERNAL_USER1`
    FOREIGN KEY (`INTERNAL_ID_USER_FK`)
    REFERENCES `PetValley`.`INTERNAL_USER` (`ID_USER_FK`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_VISIT_HOUSE_EXTERNAL_USER1`
    FOREIGN KEY (`EXTERNAL_ID_USER_FK`)
    REFERENCES `PetValley`.`EXTERNAL_USER` (`ID_USER_FK`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PetValley`.`PET_IMAGES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PetValley`.`PET_IMAGES` (
  `ID_PET_IMAGES` INT NOT NULL,
  `IMAGE` BLOB NOT NULL,
  PRIMARY KEY (`ID_PET_IMAGES`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PetValley`.`IMMUNIZATION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PetValley`.`IMMUNIZATION` (
  `ID_IMMUNIZATION` INT NOT NULL,
  `NAME_VACCINE` VARCHAR(255) NOT NULL,
  `DESCRIPTION` VARCHAR(255) NOT NULL,
  `IMMUNIZATION_DATE` DATETIME NOT NULL,
  `EXPIRATION_DATE` DATETIME NOT NULL,
  PRIMARY KEY (`ID_IMMUNIZATION`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PetValley`.`ANIMAL`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PetValley`.`ANIMAL` (
  `ID_ANIMAL` INT NOT NULL,
  `SIZE` VARCHAR(7) NOT NULL,
  `COAT` VARCHAR(5) NOT NULL,
  `AGE` VARCHAR(7) NOT NULL,
  `NEUTERED` TINYINT NOT NULL,
  `BITHDATE` DATETIME NULL,
  `VERMIFUGES` TINYINT NOT NULL,
  `ID_PET_IMAGES_FK` INT NOT NULL,
  `ID_IMMUNIZATION_FK` INT NOT NULL,
  PRIMARY KEY (`ID_ANIMAL`),
  INDEX `fk_ANIMAL_PET_IMAGES1_idx` (`ID_PET_IMAGES_FK` ASC),
  INDEX `fk_ANIMAL_IMMUNIZATION_CARD1_idx` (`ID_IMMUNIZATION_FK` ASC),
  CONSTRAINT `fk_ANIMAL_PET_IMAGES1`
    FOREIGN KEY (`ID_PET_IMAGES_FK`)
    REFERENCES `PetValley`.`PET_IMAGES` (`ID_PET_IMAGES`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ANIMAL_IMMUNIZATION_CARD1`
    FOREIGN KEY (`ID_IMMUNIZATION_FK`)
    REFERENCES `PetValley`.`IMMUNIZATION` (`ID_IMMUNIZATION`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PetValley`.`ADOPTION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PetValley`.`ADOPTION` (
  `ID_USER_FK` INT NOT NULL,
  `ID_ANIMAL_FK` INT NOT NULL,
  `ADOPTION_DATE` DATETIME NOT NULL,
  PRIMARY KEY (`ID_USER_FK`, `ID_ANIMAL_FK`),
  INDEX `fk_EXTERNAL_USER_has_ANIMAL_ANIMAL1_idx` (`ID_ANIMAL_FK` ASC),
  INDEX `fk_EXTERNAL_USER_has_ANIMAL_EXTERNAL_USER1_idx` (`ID_USER_FK` ASC),
  UNIQUE INDEX `ID_ANIMAL_FK_UNIQUE` (`ID_ANIMAL_FK` ASC),
  CONSTRAINT `fk_EXTERNAL_USER_has_ANIMAL_EXTERNAL_USER1`
    FOREIGN KEY (`ID_USER_FK`)
    REFERENCES `PetValley`.`EXTERNAL_USER` (`ID_USER_FK`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_EXTERNAL_USER_has_ANIMAL_ANIMAL1`
    FOREIGN KEY (`ID_ANIMAL_FK`)
    REFERENCES `PetValley`.`ANIMAL` (`ID_ANIMAL`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PetValley`.`TYPE_SERVICE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PetValley`.`TYPE_SERVICE` (
  `ID_TYPE_SERVICE` INT NOT NULL AUTO_INCREMENT,
  `NAME_SERVICE` VARCHAR(45) NOT NULL,
  `DESCRIPTION` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`ID_TYPE_SERVICE`),
  UNIQUE INDEX `ID_TYPE_SERVICE_UNIQUE` (`ID_TYPE_SERVICE` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PetValley`.`SERVICE_PROPOSAL`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PetValley`.`SERVICE_PROPOSAL` (
  `ID_SERVICE_PROPOSAL` INT NOT NULL AUTO_INCREMENT,
  `DATE_SERVICE` DATETIME NOT NULL,
  `APPROVED` TINYINT NOT NULL,
  `ID_TYPE_SERVICE_FK` INT NOT NULL,
  `ID_USER_FK` INT NOT NULL,
  PRIMARY KEY (`ID_SERVICE_PROPOSAL`),
  INDEX `fk_SERVICE_PROPOSAL_TYPE_SERVICE1_idx` (`ID_TYPE_SERVICE_FK` ASC),
  INDEX `fk_SERVICE_PROPOSAL_EXTERNAL_USER1_idx` (`ID_USER_FK` ASC),
  UNIQUE INDEX `ID_SERVICE_PROPOSAL_UNIQUE` (`ID_SERVICE_PROPOSAL` ASC),
  CONSTRAINT `fk_SERVICE_PROPOSAL_TYPE_SERVICE1`
    FOREIGN KEY (`ID_TYPE_SERVICE_FK`)
    REFERENCES `PetValley`.`TYPE_SERVICE` (`ID_TYPE_SERVICE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SERVICE_PROPOSAL_EXTERNAL_USER1`
    FOREIGN KEY (`ID_USER_FK`)
    REFERENCES `PetValley`.`EXTERNAL_USER` (`ID_USER_FK`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
